services:
  auth:
    build: ./auth/
    container_name: ms-auth
    environment:
      - MYSQL_HOST=database
      - MYSQL_USER=msdbuser
      - MYSQL_PORT=3306
      - MYSQL_DB=thebestdbever
      - MYSQL_PASSWORD=thedbuserpassword
    ports:
      - 5000:5000
  converter:
    container_name: ms-converter
    build: ./converter/
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PASSWORD=thesuperpassword
      - RABBIT_USER=theeternal
      - VIDEO_QUEUE=video
      - MP3_QUEUE=mp3
  gateway:
    container_name: ms-gateway
    build: ./gateway/
    environment:
      - MONGO_HOST=mongodb://localhost
      - MONGO_USER=mongooo
      - MONGO_PORT=27017
      - MONGO_DB=thebestdbever
      - RABBIT_HOST=rabbitmq
      - RABBIT_PASSWORD=thelocaluserpassword
      - RABBIT_USER=local
      - RABBIT_PORT=5432
      - VIDEO_QUEUE=video
      - MP3_QUEUE=mp3
    ports:
      - 5000:5000

  notification:
    container_name: ms-notification
    build: ./notification/
    environment:
      - MONGO_HOST=mongodb://localhost
      - MONGO_USER=mongooo
      - MONGO_PORT=27017
      - MONGO_DB=thebestdbever
      - RABBIT_HOST=rabbitmq
      - RABBIT_PASSWORD=thelocaluserpassword
      - RABBIT_USER=local
      - RABBIT_PORT=5432
      - VIDEO_QUEUE=video
      - MP3_QUEUE=mp3
      - EMAIL_ADDRESS=dev@debian.testing
      - EMAIL_PASSWORD=theultimatemegapassword
  rabbitmq:
      hostname: rabbitmq
      container_name: ms-rabbitmq
      image: rabbitmq:3.9-management
      command: rabbitmq-server
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro

  database:
    image: mysql
    restart: always
    container_name: ms-database
    volumes:
      - ./auth/init.sql:/docker-entrypoint-initdb.d/auth.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=thecoolrootpassword
      - MYSQL_USER=msdbuser
      - MYSQL_PASSWORD=thedbuserpassword
      - MYSQL_DATABASE=thebestdbever
